### ISSUE TITLE
后期可以考虑的第三方之一

### ISSUE THREAD

**Issue by yllhwa** [apachecn/BiliDriveEx#7]
参考：https://www.freebuf.com/geek/137666.html
偶然发现了百度图床的接口，这篇文章发出来接近三年了都没有挂。看到正在适配第三方，可以考虑加入，这样项目的稳定性和实用性肯定不可同日而语。

**Comment by yllhwa** [comment]
https://www.52pojie.cn/thread-1081260-1-1.html
此处在百度换肤接口也有稳定的外链

**Comment by wizardforcel** [comment]
百度的接口一般比较稳定，比如贴吧签到接口 13 年到现在没变过。

**Comment by wizardforcel** [comment]
我先适配了百家号（反正都是百度的服务器），请见 [CDNDrive](https://github.com/apachecn/CDNDrive)。
